"""Catalog helpers for the Products R&D Viewer.

The viewer can run in two modes:
- local preview: read 20_Data/products directly.
- Supabase production: use rows generated by sync_products_to_supabase.py.
"""

from __future__ import annotations

import json
import mimetypes
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import quote


IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}
REPRESENTATIVE_PRIORITY = (
    "perspective",
    "three_quarter",
    "side",
    "top",
)


def find_rnd_root(start: Path) -> Path:
    for path in [start, *start.parents]:
        if (path / "20_Data").exists() and (path / "30_Tools").exists():
            return path
    raise FileNotFoundError("RND_SKILL root not found")


def read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {"value": value}
    except Exception as exc:
        return {"error": str(exc)}


def iso_from_mtime(path: Path) -> str:
    return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc).isoformat()


def safe_rel(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def data_url(path: Path, data_dir: Path) -> str:
    return "/data/" + quote(path.relative_to(data_dir).as_posix(), safe="/")


def list_images(image_dir: Path, rnd_root: Path, data_dir: Path) -> list[dict[str, Any]]:
    if not image_dir.exists():
        return []
    images = []
    for path in sorted(image_dir.iterdir()):
        if path.suffix.lower() not in IMAGE_EXTENSIONS:
            continue
        images.append(
            {
                "asset_id": stable_asset_id(path, rnd_root),
                "name": path.name,
                "view": canonical_view(path.stem),
                "kind": image_kind(path),
                "url": data_url(path, data_dir),
                "path": safe_rel(path, rnd_root),
                "mime_type": mimetypes.guess_type(path.name)[0] or "application/octet-stream",
            }
        )
    return images


def image_kind(path: Path) -> str:
    parts = set(path.parts)
    if "optimized" in parts:
        return "optimized"
    if "source" in parts:
        return "source"
    return "run"


def canonical_view(stem: str) -> str:
    lower = stem.lower()
    if lower.startswith("three_quarter"):
        return "perspective"
    if lower.startswith("bottom"):
        return "outsole"
    if lower.startswith("back"):
        return "rear"
    return stem


def stable_asset_id(path: Path, rnd_root: Path) -> str:
    rel = safe_rel(path, rnd_root)
    return rel.replace("/", "__").replace(" ", "_")


def pick_representative_asset(assets: list[dict[str, Any]]) -> dict[str, Any] | None:
    if not assets:
        return None
    ordered = sorted(assets, key=lambda item: representative_rank(item))
    return ordered[0]


def representative_rank(asset: dict[str, Any]) -> tuple[int, int, str]:
    view = str(asset.get("view") or "").lower()
    name = str(asset.get("name") or "").lower()
    for index, preferred in enumerate(REPRESENTATIVE_PRIORITY):
        if view == preferred or name.startswith(preferred):
            return (index, 0 if asset.get("kind") != "optimized" else 1, name)
    return (99, 0 if asset.get("kind") != "optimized" else 1, name)


def latest_run_for_product(product_dir: Path) -> dict[str, Any] | None:
    candidates: list[dict[str, Any]] = []
    agent_root = product_dir / "agent_runs"
    if agent_root.exists():
        for run_dir in agent_root.iterdir():
            final_path = run_dir / "final_analysis.json"
            if run_dir.is_dir() and final_path.exists():
                final = read_json(final_path)
                candidates.append(
                    {
                        "run_id": run_dir.name,
                        "run_type": "agent_run",
                        "path": final_path,
                        "run_dir": run_dir,
                        "final": final,
                        "updated_at": iso_from_mtime(final_path),
                    }
                )
    analyses = product_dir / "analyses"
    if analyses.exists():
        for analysis_path in analyses.glob("*.json"):
            final = read_json(analysis_path)
            candidates.append(
                {
                    "run_id": analysis_path.stem,
                    "run_type": "analysis",
                    "path": analysis_path,
                    "run_dir": analysis_path.parent,
                    "final": final,
                    "updated_at": iso_from_mtime(analysis_path),
                }
            )
    if not candidates:
        return None
    return sorted(candidates, key=lambda item: item["path"].stat().st_mtime, reverse=True)[0]


def list_runs_for_product(product_dir: Path, rnd_root: Path, data_dir: Path) -> list[dict[str, Any]]:
    runs: list[dict[str, Any]] = []
    agent_root = product_dir / "agent_runs"
    if agent_root.exists():
        for run_dir in sorted((p for p in agent_root.iterdir() if p.is_dir()), key=lambda p: p.stat().st_mtime, reverse=True):
            final_path = run_dir / "final_analysis.json"
            if not final_path.exists():
                continue
            final = read_json(final_path)
            images = list_images(run_dir / "images", rnd_root, data_dir) or product_assets(product_dir, rnd_root, data_dir)
            runs.append(build_run_payload(product_dir, run_dir.name, "agent_run", final_path, final, images, rnd_root))
    analyses = product_dir / "analyses"
    if analyses.exists():
        for analysis_path in sorted(analyses.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True):
            final = read_json(analysis_path)
            images = product_assets(product_dir, rnd_root, data_dir)
            runs.append(build_run_payload(product_dir, analysis_path.stem, "analysis", analysis_path, final, images, rnd_root))
    return runs


def product_assets(product_dir: Path, rnd_root: Path, data_dir: Path) -> list[dict[str, Any]]:
    return (
        list_images(product_dir / "images" / "source", rnd_root, data_dir)
        + list_images(product_dir / "images" / "optimized", rnd_root, data_dir)
    )


def build_run_payload(
    product_dir: Path,
    run_id: str,
    run_type: str,
    final_path: Path,
    final: dict[str, Any],
    assets: list[dict[str, Any]],
    rnd_root: Path,
) -> dict[str, Any]:
    coverage_path = final_path.parent / "coverage_report.json"
    coverage = read_json(coverage_path) if coverage_path.exists() else final.get("coverage_report", {})
    return {
        "run_id": run_id,
        "product_id": product_dir.name,
        "run_type": run_type,
        "analysis_status": "complete" if final and "error" not in final else "error",
        "created_at": final.get("created_at") or iso_from_mtime(final_path),
        "updated_at": iso_from_mtime(final_path),
        "json_path": safe_rel(final_path, rnd_root),
        "final_analysis": final,
        "coverage": coverage if isinstance(coverage, dict) else {},
        "assets": assets,
    }


def product_card(product_dir: Path, rnd_root: Path, data_dir: Path) -> dict[str, Any]:
    meta_path = product_dir / "product.json"
    meta = read_json(meta_path) if meta_path.exists() else {}
    assets = product_assets(product_dir, rnd_root, data_dir)
    latest = latest_run_for_product(product_dir)
    final = latest["final"] if latest else {}
    representative = pick_representative_asset(assets)
    tags = product_tags(meta, final)
    ownership = product_ownership(meta, final)
    return {
        "product_id": product_dir.name,
        "style": product_dir.name,
        "brand": meta.get("brand") or final.get("brand") or "",
        "product_name": meta.get("product_name") or final.get("product_name") or meta.get("display_name") or product_dir.name,
        "display_name": meta.get("display_name") or final.get("product_name") or product_dir.name,
        "color": meta.get("color") or "",
        "sku": meta.get("sku") or "",
        "price": meta.get("price"),
        "currency": meta.get("currency") or "",
        "source_url": meta.get("final_url") or meta.get("source_url") or "",
        "analysis_count": len(list_runs_for_product(product_dir, rnd_root, data_dir)),
        "latest_run_id": latest["run_id"] if latest else "",
        "latest_run_updated_at": latest["updated_at"] if latest else "",
        "analysis_status": "complete" if latest else "not_analyzed",
        "representative_image_url": representative.get("url") if representative else "",
        "representative_asset_id": representative.get("asset_id") if representative else "",
        "ownership": ownership,
        "ownership_label": ownership_label(ownership),
        "category": meta.get("category") or meta.get("product_type") or final.get("category") or "",
        "season": meta.get("season") or final.get("season") or "",
        "project_code": meta.get("project_code") or meta.get("style_number") or "",
        "last_name": meta.get("last_name") or real_data_last_name(final),
        "tags": tags,
    }


def product_ownership(meta: dict[str, Any], final: dict[str, Any]) -> str:
    raw_values = [
        meta.get("ownership"),
        meta.get("owner_type"),
        meta.get("source_scope"),
        meta.get("product_scope"),
        meta.get("company_scope"),
        final.get("ownership") if isinstance(final, dict) else None,
    ]
    if any(meta.get(key) is True for key in ["is_internal", "internal", "is_own_brand"]):
        return "internal"
    if any(meta.get(key) is True for key in ["is_competitor", "competitor"]):
        return "competitor"
    for raw in raw_values:
        normalized = normalize_ownership(raw)
        if normalized:
            return normalized
    return "competitor"


def normalize_ownership(value: Any) -> str:
    raw = str(value or "").strip().lower()
    if not raw:
        return ""
    internal_values = {
        "internal",
        "own",
        "owned",
        "inhouse",
        "in-house",
        "our",
        "ours",
        "company",
        "fnf",
        "f&f",
        "self",
        "자사",
        "내부",
        "당사",
        "자체",
    }
    competitor_values = {
        "competitor",
        "external",
        "market",
        "benchmark",
        "third_party",
        "third-party",
        "other",
        "rival",
        "타사",
        "외부",
        "경쟁사",
        "벤치마크",
    }
    if raw in internal_values:
        return "internal"
    if raw in competitor_values:
        return "competitor"
    if any(token in raw for token in ["자사", "내부", "당사", "own", "internal", "inhouse", "in-house"]):
        return "internal"
    if any(token in raw for token in ["타사", "외부", "경쟁", "competitor", "external", "benchmark"]):
        return "competitor"
    return ""


def ownership_label(value: str) -> str:
    return {"internal": "자사", "competitor": "타사"}.get(value, "미분류")


def product_tags(meta: dict[str, Any], final: dict[str, Any]) -> list[str]:
    tags: list[str] = []
    for value in [ownership_label(product_ownership(meta, final)), meta.get("last_name"), meta.get("site"), meta.get("product_type"), meta.get("category"), meta.get("season"), meta.get("availability")]:
        if value:
            tags.append(str(value))
    labels = final.get("ai_labels") if isinstance(final, dict) else {}
    if isinstance(labels, dict):
        for key, value in labels.items():
            score = value.get("score") if isinstance(value, dict) else None
            if score is not None:
                tags.append(f"{key} {score}")
    return tags[:8]


def real_data_last_name(final: dict[str, Any]) -> str:
    real_data = final.get("real_data") if isinstance(final, dict) else {}
    if isinstance(real_data, dict) and real_data.get("last_name_display"):
        return str(real_data["last_name_display"])
    last_field = (
        final.get("sections", {})
        .get("last_spec", {})
        .get("last_name", {})
        if isinstance(final.get("sections"), dict)
        else {}
    )
    if isinstance(last_field, dict) and last_field.get("value"):
        return str(last_field["value"])
    return ""
